# This is a basic workflow to help you get started with Actions

name: Linux License Request

# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on: [ workflow_dispatch ]

env:
  UNITY_VERSION: 2019.4.11f1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # https://unity-ci.com/docs/github/activation
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          # Custom parameters to configure the build.
          # Parameters must start with a hyphen (-) and may be followed by a value (without hyphen). Parameters without a value will be considered booleans (with a value of true).
          customParameters: '-nographics' # <--- This is the important bit [https://github.com/webbertakken/unity-builder/issues/153]

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: License
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
